# Generated by Django 2.0.6 on 2020-04-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_evaluation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='results',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
