# Generated by Django 2.0.6 on 2020-04-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_auto_20200415_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='results',
            new_name='comments',
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./media'),
        ),
    ]
