# Generated by Django 2.0.6 on 2020-04-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_evaluation_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
