# Generated by Django 2.0.6 on 2020-04-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_auto_20200415_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='.'),
        ),
    ]
